src/MAVN.Service.SmsProviderMock/Controllers/SmsProviderMockController.cs
using System;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using MAVN.Service.NotificationSystemBroker.SmsProviderClient;
using MAVN.Service.NotificationSystemBroker.SmsProviderClient.Enums;
using MAVN.Service.SmsProviderMock.Client;
using MAVN.Service.SmsProviderMock.Client.Models;
using MAVN.Service.SmsProviderMock.Domain.Services;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace MAVN.Service.SmsProviderMock.Controllers
{
    [Route("/api/")]
    [ApiController]
    public class SmsProviderMockController : Controller, ISmsProviderMockApi, ISmsProviderApi
    {
        private readonly ISmsService _smsService;
        private readonly IMapper _mapper;

        public SmsProviderMockController(ISmsService smsService, IMapper mapper)
        {
            _smsService = smsService;
            _mapper = mapper;
        }

        /// <inheritdoc/>
        /// <response code="200">Success</response>
        [HttpPost("sms")]
        [SwaggerOperation("SendSmsAsync")]
        [ProducesResponseType((int) HttpStatusCode.OK)]
        public async Task<SmsSenderResult> SendSmsAsync(SendSmsRequestModel model)
        {
            var isSuccessful = await _smsService.CreateAsync(model.MessageId, model.PhoneNumber, model.Message);

            var result = new SmsSenderResult {Result = SmsResult.Ok};

            if (isSuccessful)
            {
                return result;
            }

            result.Result = SmsResult.Error;
            result.ErrorMessage = "Error saving to database";

            return result;
        }

        /// <inheritdoc/>
        /// <response code="200">Success</response>
        [HttpPost("sms/query/")]
        [SwaggerOperation("RetrievePaginatedSmsAsync")]
        [ProducesResponseType((int) HttpStatusCode.OK)]
        public async Task<PaginatedSmsResponseModel> RetrievePaginatedSmsAsync(PaginatedSmsRequestModel model)
        {
            var paginatedSmsModel = await _smsService.RetrievePaginatedSmsAsync(model.CurrentPage, model.PageSize, model.PhoneNumber, model.MessageId);

            return _mapper.Map<PaginatedSmsResponseModel>(paginatedSmsModel);
        }

        /// <inheritdoc/>
        /// <response code="200">Success</response>
        [HttpDelete("sms/{messageId}")]
        [SwaggerOperation("DeleteAsync")]
        [ProducesResponseType((int) HttpStatusCode.NoContent)]
        public async Task DeleteAsync(Guid messageId)
        {
            await _smsService.DeleteAsync(messageId);
        }
    }
}

src/MAVN.Service.SmsProviderMock/Controllers/SmsVisualizationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using MAVN.Service.SmsProviderMock.Domain.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace MAVN.Service.SmsProviderMock.Controllers
{
    [Route("/sentsms")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class SmsVisualizationController : Controller
    {
        private readonly ISmsRepository _smsRepository;

        public SmsVisualizationController(ISmsRepository smsRepository)
        {
            _smsRepository = smsRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var mails = await _smsRepository.GetLastFiftyTodaySmsAsync();

            return View(mails.ToList());
        }

        [HttpGet("details")]
        public async Task<IActionResult> Details(Guid messageId)
        {
            var mail = await _smsRepository.GetMessageByMessageIdAsync(messageId);

            return View(mail);
        }

    }
}

src/MAVN.Service.SmsProviderMock/Views/SmsVisualization/Details.cshtml
@model MAVN.Service.SmsProviderMock.Domain.Entities.ISms

<h1>
    @Model.PhoneNumber
</h1>
<div>
    @Model.Timestamp
</div>
<p>
    @Html.Raw(@Model.Message)
</p>

<a onclick="history.go(-1); return false;" href="#">Back</a><br />

<style>

    body {
        font-family: Arial, Helvetica, sans-serif;
    }
</style>

src/MAVN.Service.SmsProviderMock/Views/SmsVisualization/Index.cshtml
@model List<MAVN.Service.SmsProviderMock.Domain.Entities.ISms>

<table>
    <thead>
        <tr>
            <th>
                Timestamp
            </th>
            <th>
                Phone Number
            </th>
            <th>
                Message
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var email in Model)
        {
            <tr class='clickable-row' href='sentsms/details?messageId=@email.MessageId'>
                <td>@email.Timestamp</td>
                <td>@email.PhoneNumber</td>
                <td>@email.Message</td>
                <td>
                    @Html.ActionLink("Details", "Details",
                        "SmsVisualization", new { messageId = email.MessageId })
                </td>
        </tr>
    }

    </tbody>
</table>
<script>document.addEventListener("DOMContentLoaded", function (event) {

        var userSelection = document.getElementsByClassName('clickable-row');

        for(let i = 0; i < userSelection.length; i++) {
            userSelection[i].addEventListener("click",
                function() {
                    window.location = this.getAttribute("href");
                });
        }

    });</script>
<style>

    table {
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
    }

    th, td {
        padding: 10px;
        text-align: left;
    }

    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    tbody tr:hover {
        background: #d3d3d3;
        cursor: pointer;
    }
</style>